thetransylvaniandeliveryservice/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get '/products/:id', to: 'products#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  
  mount ActionCable.server => '/cable'
end

thetransylvaniandeliveryservice/app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    has_many :orders 
    has_many :comments
    
    def highest_rating_comment
        comments.rating_desc.first
    end
    def lowest_rating_comment
  	    comments.rating_asc.first
    end
    def average_rating
  	    comments.average(:rating).to_f
    end
    def viewed 
        $redis.incr("product_#{id}")
    end
    def views
        $redis.get("product_#{id}")
    end
    def self.search(search_term)
        if Rails.env.production?
            Product.where("name ilike ?", "%#{search_term}%")
        else
            Product.where("name LIKE ?", "%#{search_term}%")
        end
    end
end

thetransylvaniandeliveryservice/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
    @product.viewed
  end

  # GET /products/new
  def new
    @product = Product.new
   # redirect_to "/simple_pages/landing_page"
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :image_url, :color, :price)
  end
end

thetransylvaniandeliveryservice/app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

thetransylvaniandeliveryservice/app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

thetransylvaniandeliveryservice/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :color %><br>
    <%= form.text_field :color, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn' %>
  </div>
<% end %>

thetransylvaniandeliveryservice/app/views/products/_new_comment.html.erb
<div class="row">
  <div class="col-12 product-reviews__container-new_comment text-center">
    <% if signed_in? %>
      <h4>Add a review:</h4>
      <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
        <div class="form-group">
          <%= f.label :body, "Comments" %><br>
          <%= f.text_area :body, class:"form-control" %>
    </div>
  </div>
</div>
        <div class="rating"></div>
    <p><small>
          <%= f.submit "Submit", class:"btn" %></small>
    </p>
  <% end %>
<% end %>

thetransylvaniandeliveryservice/app/views/products/_product.html.erb
<!-- Loop the products html into the webpage -->
<!-- < % @products.each do |product| % > -->

<% cache product do %>

<div class="col-sm-4 col-md-4">
  <div class="one-prod">
    <h3>
      <%= product.name %>
    </h3>

    <h4>
      <%= image_tag(product.image_url, class: "img-responsive") unless product.image_url.blank? %>
      <p>
        <%= product.description %>
      </p>
      <p>
        Id: #<%= product.id %>
      </p>
      <p>
        Color : <%= product.color %>
      </p>
      <!--
      <p>
        <%= product.created_at %>
      </p>
      -->
      <p>
        $ <%= product.price %>
      </p>
    </h4>
    <%= link_to 'Show', product , class: "btn btn-default" %>
    <%= link_to 'Edit', edit_product_path(product) , class: "btn btn-default"  %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"  %>
  </div>
</div><!-- /col -->

<% end %>

thetransylvaniandeliveryservice/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

thetransylvaniandeliveryservice/app/views/products/index.html.erb
<h1>Listing products</h1>
<br>

<div class="row">
  <% cache(cache_key_for_products) do %>
    <%= render @products %>
  <% end %>
</div>

<%= link_to 'New Product', new_product_path %>

thetransylvaniandeliveryservice/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

thetransylvaniandeliveryservice/app/views/products/show.html.erb
<section class="container-fluid">
  <div class="row" data-product-id="<%= @product.id %>">

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@product.image_url, class: "img-fluid", class: "img-zoom") if @product.image_url.present? %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:$</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Views:</strong>
  <%= @product.views %>
</p>

<p>
  <% if user_signed_in? %>
    <%= form_with(url: payments_create_path) do |form| %>
      <%= hidden_field_tag(:product_id, @product.id) %>
      <%= render partial: "shared/stripe_checkout_button" %>
    <% end %>
  <% end %>
</p>

<p>Average Rating: id="average-rating" data-score="<%= @product.average_rating %>"></div> </p>
<%= @product.highest_rating_comment %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= link_to "Show Product", product_path(3) %>
<!-- generates the HTML tag: -->
<a href=”/products/3>Show Product</a>
<%= render 'new_comment' %>
<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
<%= render 'comments' %>

<%= will_paginate @comments %>