thetransylvaniandeliveryservice/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get '/products/:id', to: 'products#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  
  mount ActionCable.server => '/cable'
end

thetransylvaniandeliveryservice/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  scope :rating_desc, -> { order(rating: :desc) }
  scope :rating_asc, -> { order(rating: :asc) }

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }

  after_create_commit { CommentUpdateJob.perform_later(self, self.user) }
end

thetransylvaniandeliveryservice/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = current_user
    respond_to do |format|
      if @comment.save
        ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        ProductChannel.broadcast_to @product.id, comment: @comment, average_rating: @product.average_rating
        format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end

end

thetransylvaniandeliveryservice/app/helpers/comments_helper.rb
module CommentsHelper
end

thetransylvaniandeliveryservice/app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p>
    <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if current_user && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
</div>

thetransylvaniandeliveryservice/app/views/comments/create.js.erb
$("#new_comment").html("Thank you for your review!");

$("#average-rating").attr('data-score', "<%= @product.average_rating %>");

refreshRating();